[phases.setup]
nixPkgs = ["php81", "php81.extensions.curl", "php81.extensions.mbstring", "php81.extensions.xml", "php81.extensions.openssl"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php -S 0.0.0.0:${PORT:-8000} -t public"